---
- shell: "getent passwd '{{ developer_uid }}' | cut -d: -f1 | tr -d '\n'"
  register: unix_user_developer

- name: Ensure group developer exists
  group:
    name: "developer"
    state: present
  when: unix_user_developer.stdout != "" && unix_user_developer.stdout != developer_username

- name: Move home directory
  user:
    name: "{{ unix_user_developer.stdout }}"
    home: "/home/{{ developer_username }}"
    move_home: yes
  when: unix_user_developer.stdout != "" && unix_user_developer.stdout != developer_username

- name: Rename user
  command: "usermod --login {{ unix_user_developer.stdout }} {{ developer_username }}"
  when: unix_user_developer.stdout != "" && unix_user_developer.stdout != developer_username

- name: Add the user '{{ developer_username }}' with the {{ developer_uid }} uid and a primary group of 'developer'
  user:
    comment: Unnamed User
    name: "{{ developer_username }}"
    group: developer
    uid: "{{ developer_uid }}"
    groups: [sudo]
    shell: /bin/bash
  register: developer_user_info

- name: Add the user '{{ developer_username }}' with the {{ developer_uid }} uid and a primary group of 'developer'
  user:
    comment: Unknown Developer
    name: "{{ developer_username }}"
    uid: "{{ developer_uid }}"
    groups: [sudo]
    shell: /bin/bash
  register: developer_user_info

- name: Set developer_username to exist user
  set_fact:
    developer_username: "{{ developer_user_info.name }}"

- name: Change user password
  user:
    name: '{{ developer_username }}'
    update_password: always
    password: "{{ developer_password | password_hash('sha512') }}"

- name: Allow root password login via ssh
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^.*PermitRootLogin.*$'
    replace: 'PermitRootLogin yes'

- name: Dissalow root password login via ssh
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^.*PasswordAuthentication.*$'
    replace: 'PasswordAuthentication no'

- name: 'Set ClientAliveInterval to 3600'
  lineinfile:
    path: '/etc/ssh/sshd_config'
    line: 'ClientAliveInterval 3600'

- name: Restarting sshd
  set_fact:
    service_restarted: "{{ service_restarted + [ 'sshd' ] }}"

- name: "Ensure ownerships"
  file:
    dest: "{{ developer_user_info.home }}"
    owner: "{{ developer_username }}"
    recurse: true
  when: developer_user_info.home is regex('^/home/.*')
