---
- name: Check if homebrew directory exists
  stat:
    path: "/home/linuxbrew/.linuxbrew"
  register: stat_home_linuxbrew

- name: create homebrew directory
  become: true
  file:
    path: "/home/linuxbrew"
    state: directory
    owner: "{{ developer_username }}"
    mode: 0700
  when: not stat_home_linuxbrew.stat.exists

# - name: install homebrew
#   shell: |
#     NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#   become: true
#   become_user: "{{ developer_username }}"
#   when: not stat_home_linuxbrew.stat.exists

- name: get homebrew version
  shell: "echo $(curl -H 'Authorization: {{ github_oauth_token }}' -L --silent https://api.github.com/repos/Homebrew/brew/releases | jq -r '.[].tag_name' | grep -v '\\-rc[0-9]*' | head -1)"
  register: homebrew_version_output

- name: install homebrew
  shell: |
    export DEBIAN_FRONTEND=noninteractive
    export BREW_VERSION="{{ homebrew_version_output.stdout }}"
    git clone --branch ${BREW_VERSION} --single-branch --depth 1 https://github.com/Homebrew/brew /home/linuxbrew/.linuxbrew/Homebrew \
    && mkdir -p /home/linuxbrew/.linuxbrew/etc \
    /home/linuxbrew/.linuxbrew/include \
    /home/linuxbrew/.linuxbrew/lib \
    /home/linuxbrew/.linuxbrew/opt \
    /home/linuxbrew/.linuxbrew/sbin \
    /home/linuxbrew/.linuxbrew/share \
    /home/linuxbrew/.linuxbrew/var/homebrew/linked \
    /home/linuxbrew/.linuxbrew/Cellar \
    /home/linuxbrew/.linuxbrew/bin \
    /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/ \
    && ln -s ../Homebrew/bin/brew /home/linuxbrew/.linuxbrew/bin/
  become: true
  become_user: "{{ developer_username }}"
  when: not stat_home_linuxbrew.stat.exists

- name: check if homebrew core tap exists
  stat:
    path: "/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core"
  register: stat_home_core_tap

- name: remove homebrew core tap
  file:
    path: "/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core"
    state: absent
  when: stat_home_core_tap.stat.exists

- name: ensure homebrew core tap
  shell: |
    export DEBIAN_FRONTEND=noninteractive
    git clone --single-branch --depth 1 https://github.com/Homebrew/homebrew-core /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
  become: true
  become_user: "{{ developer_username }}"

- name: Configure profiles
  become: true
  lineinfile:
    create: yes
    dest: '{{ developer_user_info.home }}/{{item}}'
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
  with_items: ['.zprofile', '.profile']

- name: "Ensure git-ssh"
  command: "/home/linuxbrew/.linuxbrew/bin/brew install digitalspacestdio/git-ssh/git-ssh"
  become: true
  become_user: "{{ developer_username }}"

- name: "Ensure nvm"
  command: "/home/linuxbrew/.linuxbrew/bin/brew install nvm"
  become: true
  become_user: "{{ developer_username }}"

- name: "Ensure nvm path"
  command: "/home/linuxbrew/.linuxbrew/bin/brew --prefix nvm"
  register: brew_nvm_prefix_output
  become: true
  become_user: "{{ developer_username }}"

- name: "Updating profiles"
  blockinfile:
    dest: '{{ developer_user_info.home }}/{{item}}'
    marker: "# {mark} nvm"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "{{ brew_nvm_prefix_output.stdout }}/nvm.sh" ] && . "{{ brew_nvm_prefix_output.stdout }}/nvm.sh"
      [ -s "{{ brew_nvm_prefix_output.stdout }}/etc/bash_completion.d/nvm" ] && . "{{ brew_nvm_prefix_output.stdout }}/etc/bash_completion.d/nvm"
  with_items: ['.zshrc', '.bashrc']
  become: true
  become_user: "{{ developer_username }}"

- name: "Ensure SDKMAN"
  shell: 'curl -s "https://get.sdkman.io" | bash'
  become: true
  become_user: "{{ developer_username }}"
    
- name: "Adding SDKMAN to profiles"
  blockinfile:
    dest: '{{ developer_user_info.home }}/{{item}}'
    marker: "# {mark} sdkman"
    block: |
      source "$HOME/.sdkman/bin/sdkman-init.sh"
  with_items: ['.zprofile', '.profile']

- name: "Installing golang"
  shell: runuser -l {{ developer_username }} -c "brew install go"
  become: true
    
- name: "Adding GOPATH to profiles"
  blockinfile:
    dest: '{{ developer_user_info.home }}/{{item}}'
    marker: "# {mark} golang"
    block: |
      export GOPATH="${HOME}/go"
      export PATH="${PATH}:${GOPATH}/bin"
  with_items: ['.zprofile', '.profile']
  become: true
  become_user: "{{ developer_username }}"

- name: "Installing jenv"
  shell: runuser -l {{ developer_username }} -c "brew install jenv"
  become: true
    
- name: "Adding jenv to profiles"
  blockinfile:
    dest: '{{ developer_user_info.home }}/{{item}}'
    marker: "# {mark} jenv"
    block: |
      export PATH="$HOME/.jenv/bin:$PATH"
      if which jenv > /dev/null; then eval "$(jenv init -)"; fi
  with_items: ['.zprofile', '.profile']
  become: true
  become_user: "{{ developer_username }}"

- name: "Installing additional packages"
  shell: runuser -l {{ developer_username }} -c "brew install {{ item }}"
  become: true
  with_items: 
    - hadolint